name: Build Chrome Extension

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: stage files
        run: |
          mkdir -p extension
          find . -maxdepth 1 -type f -not -path "./.*" -exec cp {} extension/ \;
          mkdir -p extension/fonts extension/images extension/src extension/views
          cp -r fonts/* extension/fonts/ 2>/dev/null || :
          cp -r images/* extension/images/ 2>/dev/null || :
          cp -r src/* extension/src/ 2>/dev/null || :
          cp -r views/* extension/views/ 2>/dev/null || :

      - name: create zip
        run: |
          cd extension
          zip -r ../fuckyouwebsite.zip *
          cd ..
          cp fuckyouwebsite.zip fuckyouwebsite.crx

      - name: upload crx
        uses: actions/upload-artifact@v4
        with:
          name: fuckyouwebsite.crx
          path: |
            fuckyouwebsite.crx

      - name: make version
        id: version
        run: echo ::set-output name=version::$(date +'%Y%m%d%H%M%S')

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
